#!/usr/bin/env ruby

require 'optparse'
require_relative "../lib/with_ethics"
include WithEthics

params = {}  # for parameters to pass on to run unit
option_parser = OptionParser.new do |opts|
  opts.on( '-h', '--help', 'Display this screen' ) do
    puts opts
    exit
  end
    
  opts.on('-f', '--file <path/to/config/file>', String, "specify config to use. Default = ./promises.yml") do |f|
    params[:config_file] = f
  end
  
  opts.on('-r', '--root <path to project root>', String, 'Specify file system root. Default is current') do |root|
    params[:root] = root
  end
  
  opts.on('-s', '--silent', "Suppresses all output. Mostly used for testing") do
    params[:output_to] = []
  end
end

option_parser.parse!

params[:config_file] ||= params[:root].nil? ? "promises.yml" : "#{ params[:root] }/promises.yml"

execute!(params)
