#!/usr/bin/env ruby

require 'optparse'
require_relative "../lib/with_ethics"
include WithEthics

params = {}  # for parameters to pass on to run unit
option_parser = OptionParser.new do |opts|
  opts.on( '-h', '--help', 'Display this screen' ) do
    puts opts
    exit
  end
    
  opts.on('-f', '--file <path/to/config/file>', String, "specify config to use. Default = ./promises.yml") do |f|
    params[:config_file] = f
  end
end

option_parser.parse!

params[:skip] ||= false
params[:config_file] ||= "promises.yml"
execute!(params)
